import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './components/Providers';
import AppBar from './components/AppBar';
import SignInPannel from './components/SignInPannel';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: {
		absolute: '',
		template: '%s | SRG Real State',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<AppBar>
						<SignInPannel />
					</AppBar>
					{children}
					<ToastContainer />
				</Providers>
			</body>
		</html>
	);
}
